apps/blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.conf import settings
from .views import test_page_view
from .views import (IndexView, DetailView, CategoryView, TagView, AboutView,
                    SilianView, MySearchView, ArchiveView, TimelineView, DetailEditView,
                    update_article, FriendLinkView, friend_add, SubjectDetailView,
                    SubjectPageDetailView, SubjectListView, dashboard, feed_hub)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # 主页，自然排序
    path('article/<slug:slug>/', DetailView.as_view(), name='detail'),  # 文章内容页
    path('article-edit/<slug:slug>/', DetailEditView.as_view(), name='article_edit'),  # 文章编辑
    path('article-update/', update_article, name='article_update'),  # 文章更新
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('tag/<slug:slug>/', TagView.as_view(), name='tag'),
    path('about/', AboutView, name='about'),  # About页面
    path('timeline/', TimelineView.as_view(), name='timeline'),  # timeline页面
    path('archive/', ArchiveView.as_view(), name='archive'),  # 归档页面
    path('silian.xml', SilianView.as_view(content_type='application/xml'), name='silian'),  # 死链页面
    path('search/', MySearchView.as_view(), name='search_view'),  # 全文搜索
    path('friend/', FriendLinkView.as_view(), name='friend'),  # 友情链接
    path('friend/add/', friend_add, name='friend_add'),  # 友情链接申请
    path('dashboard/', dashboard, name='dashboard'),  # 看板
    path('feed-hub/', feed_hub, name='feedhub'),  # feed hub

    # 专题列表页
    path('subject/', SubjectListView.as_view(), name='subject_index'),
    # 专题详情页
    path('subject/<int:pk>/', SubjectPageDetailView.as_view(), name='subject_page'),
    # 专题文章内容页
    path('subject/article/<slug:slug>/', SubjectDetailView.as_view(), name='subject_detail'),

]

if settings.DEBUG:
    urlpatterns.append(path('test/', test_page_view, name='test'))

izone/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from blog.feeds import AllArticleRssFeed
from blog.views import robots

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
                  path('favicon.ico', RedirectView.as_view(url='/static/blog/img/favicon.svg')),
                  path('adminx/', admin.site.urls),
                  path('accounts/', include('allauth.urls')),  # allauth
                  path('accounts/', include(('oauth.urls', 'oauth'), namespace='oauth')),
                  # oauth,只展现一个用户登录界面
                  path('', include(('blog.urls', 'blog'), namespace='blog')),  # blog
                  path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
                  # comment
                  path('robots.txt', robots, name='robots'),  # robots
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
                       name='django.contrib.sitemaps.views.sitemap'),  # 网站地图
                  path('feed/', AllArticleRssFeed(), name='rss'),  # rss订阅
                  path('resume/', include(('resume.urls', 'resume'), namespace='resume')),  # 个人简历
                  path('nav/', include(('webstack.urls', 'webstack'), namespace='webstack')),

                  path('rss/', include(('rsshub.urls', 'rsshub'), namespace='rsshub')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

if settings.API_FLAG:
    from api.urls import router

    urlpatterns.append(path('api/v1/', include((router.urls, router.root_view_name),
                                               namespace='api')))  # restframework

if settings.TOOL_FLAG:
    urlpatterns.append(path('tool/', include(('tool.urls', 'tool'), namespace='tool')))  # tool

apps/blog/models.py
import json
from datetime import datetime
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import markdown
import re


# Create your models here.

# 文章关键词，用来作为SEO中keywords
class Keyword(models.Model):
    name = models.CharField('文章关键词', max_length=20)

    class Meta:
        verbose_name = '关键词'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name


# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240, default='标签描述',
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag', kwargs={'slug': self.slug})

    def get_article_list(self):
        """返回当前标签下所有发表的文章列表"""
        return Article.objects.filter(tags=self, is_publish=True)


# 文章分类
class Category(models.Model):
    name = models.CharField('文章分类', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240, default='分类描述',
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})

    def get_article_list(self):
        return Article.objects.filter(category=self, is_publish=True)


# 专题
class Subject(models.Model):
    STATUS_CHOICES = (
        ('not_started', '未开始'),
        ('ongoing', '连载中'),
        ('completed', '已完结'),
    )

    name = models.CharField('专题名称', max_length=50)
    status = models.CharField('状态', max_length=20, choices=STATUS_CHOICES, default='not_started')
    description = models.CharField('描述', max_length=250)
    sort_order = models.IntegerField('排序', default=99, help_text='作为专题列表页的排序')
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    cover_image = ProcessedImageField(upload_to='subject/upload/%Y/%m/%d/',
                                      default='subject/default/default.png',
                                      verbose_name='封面图',
                                      processors=[ResizeToFill(250, 150)],
                                      help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px'
                                      )

    class Meta:
        verbose_name = '专题'
        verbose_name_plural = verbose_name
        ordering = ['sort_order']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:subject_page', kwargs={'pk': self.pk})

    def get_topics(self):
        """得到一个专题的所有主题，按照排序进行排序"""
        return Topic.objects.filter(subject=self).order_by('sort_order', '-pk')

    def get_article_count(self):
        """获取专题下文章数量"""
        num = 0
        for each in self.get_topics():
            num += each.get_articles().count()
        return num

    def get_article_list(self):
        """
        返回一个专题下文章的列表，这个跟显示的一致，可以用来得到上下文
        @return:
        """
        article_list = []
        for topic in self.get_topics():
            article_list.extend(topic.get_articles())
        return article_list

    def get_status_color(self):
        """返回对应状态的颜色"""
        text_dict = {
            'not_started': 'danger',
            'ongoing': 'info',
            'completed': 'success'
        }
        return text_dict[self.status]


# 专题的主题，作为专题的目录，专题-主题-文章
class Topic(models.Model):
    name = models.CharField('主题名称', max_length=50)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    sort_order = models.IntegerField('排序', default=99, help_text='仅作为主题在专题中的排序，类似目录')

    subject = models.ForeignKey(Subject, verbose_name='所属专题', on_delete=models.PROTECT,
                                related_name='topics')

    class Meta:
        verbose_name = '专题-主题'
        verbose_name_plural = verbose_name
        ordering = ['sort_order']

    def __str__(self):
        return f'[{self.subject.name}]{self.name}'

    def get_absolute_url(self):
        return reverse('blog:subject_page', kwargs={'pk': self.subject.pk}) + f'#{self.name}'

    def get_articles(self):
        """得到一个主题的所有已发布的文章，按照主题排序排序"""
        return Article.objects.filter(is_publish=True, topic=self).order_by('topic_order', '-pk')


# 文章
class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者',
                               on_delete=models.PROTECT)
    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField('文章摘要', max_length=230, default='文章摘要等同于网页description内容，请务必填写...')
    body = models.TextField(verbose_name='文章内容')
    img_link = ProcessedImageField(upload_to='article/upload/%Y/%m/%d/',
                                   default='article/default/default.png',
                                   verbose_name='封面图',
                                   processors=[ResizeToFill(250, 150)],
                                   blank=True,
                                   help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px'
                                   )
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    views = models.IntegerField('阅览量', default=0)
    slug = models.SlugField(unique=True)
    is_top = models.BooleanField('置顶', default=False)
    is_publish = models.BooleanField('是否发布', default=True)

    category = models.ForeignKey(Category, verbose_name='文章分类', on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    keywords = models.ManyToManyField(Keyword, verbose_name='文章关键词',
                                      help_text='文章关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够')

    # 跟专题-主题相关的字段和关系，都是非必填，仅给专题的时候使用，其他地方一概不用
    # 设计上一个专题有多个主题（目录的概念），一个主题可以有多个文章，一个文章只能归属一个主题
    topic = models.ForeignKey(Topic, verbose_name='所属主题', on_delete=models.SET_NULL,
                              null=True, blank=True, related_name='articles')
    topic_order = models.IntegerField('主题中排序', default=99, null=True, blank=True,
                                      help_text='仅作为文章在主题中的排序')
    topic_short_title = models.CharField('主题短标题', max_length=50, null=True, blank=True,
                                         help_text='专门给Topic使用的短标题')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return f'{self.title[:30]}...' if len(self.title) > 30 else self.title

    def save(self, *args, **kwargs):
        # 当为更新且is_publish由False变更成True的时候才执行: 发布的文章时间的创建时间以发布时间为准
        if self.pk and self.is_publish and Article.objects.filter(pk=self.pk,
                                                                  is_publish=False).exists():
            self.create_date = datetime.now()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """优先使用专题地址"""
        if self.topic:
            return self.get_subject_absolute_url()
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def get_subject_absolute_url(self):
        """获取专栏地址"""
        return reverse('blog:subject_detail', kwargs={'slug': self.slug})

    def body_to_markdown(self):
        return markdown.markdown(self.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self):
        """
        有主题则只能返回这个主题所属专题下的文章，否则返回空，没有主题则按照pk返回
        @return:
        """
        if self.topic:
            subject_articles = self.topic.subject.get_article_list()
            for index, article in enumerate(subject_articles):
                if article.pk == self.pk and index != 0:
                    return subject_articles[index - 1]
            return

        return Article.objects.filter(id__lt=self.id, is_publish=True).order_by('-id').first()

    def get_next(self):
        if self.topic:
            subject_articles = self.topic.subject.get_article_list()
            for index, article in enumerate(subject_articles):
                if article.pk == self.pk and index != len(subject_articles) - 1:
                    return subject_articles[index + 1]
            return

        return Article.objects.filter(id__gt=self.id, is_publish=True).order_by('id').first()

    def get_topic_title(self):
        """仅当有主题的时候优先使用短标题，这个函数给专题使用"""
        if self.topic:
            return self.topic_short_title or self.title
        return self.title


# 时间线
class Timeline(models.Model):
    COLOR_CHOICE = (
        ('primary', '基本-蓝色'),
        ('success', '成功-绿色'),
        ('info', '信息-天蓝色'),
        ('warning', '警告-橙色'),
        ('danger', '危险-红色')
    )
    SIDE_CHOICE = (
        ('L', '左边'),
        ('R', '右边'),
    )
    STAR_NUM = (
        (1, '1颗星'),
        (2, '2颗星'),
        (3, '3颗星'),
        (4, '4颗星'),
        (5, '5颗星'),
    )
    side = models.CharField('位置', max_length=1, choices=SIDE_CHOICE, default='L')
    star_num = models.IntegerField('星星个数', choices=STAR_NUM, default=3)
    icon = models.CharField('图标', max_length=50, default='fa fa-pencil')

apps/blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% load static %}

{% block head_title %}关于网站，网站及博主介绍{% endblock %}
{% block metas %}
    <meta name="description"
          content="本网站是一个采用django+bootstrap4搭建的个人博客，本着学习和分享的精神，博客项目开源，源代码可以到我的Github中查看，网站建站历程可以查看页面Timeline内容。">
    <meta name="keywords" content="网站About页面,关于网站,关于博主,关于站长">
{% endblock %}
{% block top-file %}
    <style>
        .card img {
            max-width: 100%;
        }
    </style>
{% endblock %}


{% block base_content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8" style="line-height:2">
                <div class="card rounded-6 border-0 p-3 f-16">{{ body|safe }}</div>
            </div>
            <div class="col-lg-4">
                {% include 'blog/tags/base_right.html' %}
            </div>
        </div>
    </div>
{% endblock %}

apps/blog/templates/blog/articleEdit.html
{% extends 'blog/base.html' %}
{% load static tool_tags %}
{% block head_title %}{{ article.title }}_{{ article.category }}{% endblock %}
{% block metas %}
    <meta name="robots" content="noindex">
    <meta name="description" content="{{ article.summary }}">
{% endblock %}
{% block top-file %}
    <link rel="stylesheet" href="{% static 'editor/css/editormd.min.css' %}"/>
    <style>
        #layout > header {
            margin: 0 auto;
            padding: 5px 0;
            width: 90%;
        }

        #layout > header {
            margin-bottom: 1rem;
        }

        #layout > header > div > a {
            color: inherit;
            text-decoration: none;
        }

        #layout > header > div > a:hover {
            color: #ea6f5a;
        }

    </style>
{% endblock %}
{% block base_content %}
    <div id="layout">
        <header class="my-2">
            <form class="form-inline">
                <button type="button" class="btn btn-success btn-sm mr-2" id="save-article">保存修改</button>
                <button type="button" class="btn btn-warning btn-sm mr-2" id="back-article">放弃编辑</button>
                <button type="button" class="btn btn-info btn-sm mr-2" id="more-edit-article">后台编辑</button>
                <input type="text" class="form-control form-control-sm mr-2"
                       id="article-img-link" style="min-width: 25rem"
                       value="{{ article.img_link }}">
                <input class="form-check-input" type="checkbox" id="change-img-link-flag">
                <label class="form-check-label" for="autoSizingCheck" title="勾选之后保存才会更新封面图链接">更新封面图链接</label>
            </form>
        </header>
        <div id="test-editormd">
            <textarea style="display:none;">{{ article.body }}</textarea>
        </div>
    </div>
{% endblock %}
{% block end_file %}
    <script src="{% static 'blog/js/jq/3.3.1/jquery.min.js' %}"></script>
    <script src="{% static 'editor/js/editormd.min.js' %}"></script>
    <script type="text/javascript">
        let testEditor;

        $(function () {
            testEditor = editormd("test-editormd", {
                width: "90%",
                height: "1000",
                syncScrolling: "single",
                path: "{% static 'editor/lib/' %}"
            });
        });
    </script>
    <script src="{% static 'blog/js/article.js' %}?v={{ static_version.js_blog_article }}"></script>
    <script>
        $('#save-article').click(function () {
            article_update_save("{{ csrf_token }}", "{% url 'blog:article_update' %}", "{{ article.slug }}")
        });
        $('#back-article').click(function () {
            window.location.href = "{% url 'blog:detail' article.slug %}";
        });
        $('#more-edit-article').click(function () {
            window.location.href = "{% url 'admin:blog_article_change' article.pk %}";
        });
    </script>
{% endblock %}

apps/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags static comment_tags %}
{% load humanize %}

{% block head_title %}{{ article.title }}_{{ article.category }}{% endblock %}
{% block metas %}
    <meta name="description" content="{{ article.summary }}">
    <meta name="keywords" content="{% keywords_to_str article %}">
    {#SEO优化#}
    <meta property="og:locale" content="zh_CN" />
    <meta property="og:site_name" content="{{ site_end_title }}" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="{{ article.title }}_{{ article.category }}" />
    <meta property="og:url" content="{{ site_url }}{{ article.get_absolute_url }}" />
    <meta property="og:image" content="{{ site_url }}{{ article.img_link.url }}" />
    <meta property="og:image:secure_url" content="{{ site_url }}{{ article.img_link.url }}" />
    <meta property="og:image:width" content="250" />
    <meta property="og:image:height" content="150" />
    <meta property="article:published_time" content="{{ article.create_date | date:"Y-m-d" }}T{{ article.create_date | time:"H:i:s" }}+00:00" />
    <meta property="article:modified_time" content="{{ article.update_date | date:"Y-m-d" }}T{{ article.update_date | time:"H:i:s" }}+00:00" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="{{ article.title }}_{{ article.category }}" />
    <meta name="twitter:image" content="{{ site_url }}{{ article.img_link.url }}" />
    {#SEO优化#}
{% endblock %}


{% block top-file %}
    {#    <script>var stop_headroom = true;</script>#}
    {% if user.is_authenticated %}
        <link href="{% static 'blog/simplemde/1.11.2/simplemde.min.css' %}" rel="stylesheet">
    {% endif %}
    <link href="{% static 'blog/css/detail.css' %}?v={{ static_version.css_blog_detail }}" rel="stylesheet">
    <link href="{% static 'blog/css/monokai-2.css' %}?v=20240206.02" rel="stylesheet">
    <link href="{% static 'comment/css/base_comment.css' %}?v=20190114.554" rel="stylesheet">
{% endblock %}

{% block base_content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-9">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-white border-0 rounded-6 mb-2 py-2 f-15">
                        <li class="breadcrumb-item">
                            <i class="fa fa-home mr-1"></i><a href="{% url 'blog:index' %}">首页</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href="{{ article.category.get_absolute_url }}">{{ article.category }}</a>
                        </li>
                        <li class="breadcrumb-item active d-none d-md-block" aria-current="page">
                            {% if user.is_superuser or user == article.author %}
                                <a class="edit-blog" href="{% url 'blog:article_edit' article.slug %}"
                                   target="_blank" title="编辑文章">
                                    {{ article.title|my_slice:":50" }}</a>
                            {% else %}
                                {{ article.title|my_slice:":50" }}
                            {% endif %}

                        </li>
                        <li class="breadcrumb-item active d-md-none" aria-current="page">
                            {% if user.is_superuser or user == article.author %}
                                <a class="edit-blog" href="{% url 'blog:article_edit' article.slug %}"
                                   target="_blank" title="编辑文章">当前文章</a>
                            {% else %}
                                当前文章
                            {% endif %}
                        </li>
                    </ol>
                </nav>
                <div class="card rounded-6 border-0" id="article">
                    <div class="card-body px-2 px-md-3 pb-0">
                        <h1 class="card-title text-center font-weight-bold text-info">{{ article.title }}</h1>
                        <hr>
                        <div class="text-center f-13">
                        <span class="mx-2" data-toggle="tooltip" data-placement="bottom"
                              title="最后编辑于{{ article.update_date|date:'Y年m月d日' }}">发表于 {{ article.create_date|date:'Y年m月d日' }}</span>
                            <span class="mx-2">阅读 {{ article.views }}</span>
                            <span class="mx-2">评论 {{ article.article_comments.count }}</span>
                        </div>
                        <div class="article-body mt-4 f-17" style="line-height:1.8">
                            {{ article.body|safe }}
                            <blockquote class="p-1 f-14" style="border-left: 4px solid #dc3545;">
                                <p class="m-1"><strong>版权声明：</strong>如无特殊说明，文章均为本站原创，转载请注明出处</p>
                                <p class="m-1"><strong>本文链接：</strong>{{ site_url }}{{ article.get_absolute_url }}</p>
                                <p class="m-1"><strong>许可协议：</strong><a
                                        href="https://creativecommons.org/licenses/by-nc/4.0/">署名-非商业性使用 4.0 国际许可协议</a>
                                </p>
                            </blockquote>
                        </div>
                        <div class="tag-cloud my-4">
                            {% for tag in article.tags.all %}
                                <a class="tags f-16" href="{{ tag.get_absolute_url }}">#{{ tag.name }}</a>
                            {% endfor %}
                        </div>
                        {% include 'blog/tags/reward.html' %}
                    </div>
                </div>
                <div class="card mt-2 rounded-6 border-0" id="comment-block">
                    {% include 'comment/comment_form.html' %}
                    {% get_parent_comments article as comment_list %}
                    {% include 'comment/comment_list.html' %}
                </div>
            </div>
            <div class="col-lg-3">
                <div class="article-toc d-none d-lg-block f-14 rounded-6">
                    <div class="toc-title f-15"><strong>大纲</strong></div>
                    {{ article.toc|safe }}
                </div>
            </div>
        </div>
    </div>
    <!--图片预览-->
    <div class="modal fade" id="img-to-big" tabindex="-1" role="dialog" aria-labelledby="img-to-bigTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 90%">
            <img class="rounded mx-auto d-block" alt="image" style="max-width: 100%">
        </div>
    </div>
    <!--前后文章-->
    {% if article.get_pre %}
        <div class="more-blog" id="icon-pre-blog">
            <a href="{{ article.get_pre.get_absolute_url }}" title="上一篇：{{ article.get_pre.title }}">
                <i class="fa fa-angle-left fa-3x"></i>
            </a>
        </div>
    {% endif %}
    {% if article.get_next %}
        <div class="more-blog" id="icon-next-blog">
            <a href="{{ article.get_next.get_absolute_url }}" title="下一篇：{{ article.get_next.title }}">
                <i class="fa fa-angle-right fa-3x"></i>
            </a>
        </div>
    {% endif %}
    <!--跳转到评论按钮-->
    <div class="text-center" id="go-to-com" title="查看评论" href="#comment-block"><i class="fa fa-commenting"></i></div>
{% endblock %}

{% block end_file %}
    <script src="{% static 'blog/js/code.js' %}?v={{ static_version.js_blog_code }}"></script>
    <script>
        {#文章里面的外链单独打开#}
        const links = document.querySelectorAll('#article a');
        links.forEach(link => {
            link.setAttribute('target', '_blank');
        });
        {#第一个标题自动激活#}
        document.addEventListener('DOMContentLoaded', function () {
            const firstLi = document.querySelector('div.article-toc div.toc > ul > li > a:first-child');
            if (firstLi) {
                firstLi.classList.add('active');
            }
        });
    </script>
    {% if user.is_authenticated %}
        <script src="{% static 'blog/simplemde/1.11.2/simplemde.min.js' %}"></script>
        <script src="{% static 'comment/js/editor.js' %}?v=20230516.1"></script>
        <script src="{% static 'comment/js/activate-power.js' %}?v=20180120"></script>
        <script>
            var sw = window.screen.width;
            if (sw > 1200) {
                POWERMODE.colorful = true;
                POWERMODE.shake = false;
                document.body.addEventListener('input', POWERMODE)
            }
        </script>
    {% endif %}
{% endblock %}

apps/blog/templates/blog/friend.html
{% extends 'blog/base.html' %}
{% load static blog_tags %}

{% block head_title %}友情链接，申请友联{% endblock %}

{% block metas %}
    <meta name="description"
          content="本网站是一个采用django+bootstrap4搭建的个人博客，本着学习和分享的精神，博客项目开源，源代码可以到我的Github中查看，网站建站历程可以查看页面Timeline内容。">
    <meta name="keywords" content="friend页面,友情链接,申请友联">
{% endblock %}

{% block top-file %}
{% endblock %}

{% block base_content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-10">
                <div class="friend-block">
                    <h2 class="text-info"><a href="{% url 'blog:friend_add' %}">申请友链</a></h2>
                    <div class="friend-list">
                        {% for friend in friend_list %}
                            <a href="{{ friend.get_home_url }}" target="_blank">
                                <div class="friend-container"
                                     style='background-image: url("{{ friend.logo.url }}");'>
                                    <div class="friend-img">
                                        <img src="{{ friend.logo.url }}" alt="{{ friend.description }}">
                                        <div class="friend-description">
                                            {{ friend.description|my_slice:":23" }}
                                        </div>
                                    </div>
                                    <div class="friend-title"><span>{{ friend.name }}</span></div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                    {% get_friends False True as not_show_friends %}
                    {% if not_show_friends %}
                        <h2>失联友链</h2>
                        <div class="friend-list not-show-friend">
                            {% for friend in not_show_friends %}
                                <a>
                                    <div class="friend-container"
                                         style='background-image: url("{{ friend.logo.url }}");'>
                                        <div class="friend-img">
                                            <img src="{{ friend.logo.url }}" alt="{{ friend.description }}">
                                            <div class="friend-description">{{ friend.not_show_reason }}</div>
                                        </div>
                                        <div class="friend-title"><span>{{ friend.name }}</span></div>
                                    </div>
                                </a>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}