apps/blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.conf import settings
from .views import test_page_view
from .views import (IndexView, DetailView, CategoryView, TagView, AboutView,
                    SilianView, MySearchView, ArchiveView, TimelineView, DetailEditView,
                    update_article, FriendLinkView, friend_add, SubjectDetailView,
                    SubjectPageDetailView, SubjectListView, dashboard, feed_hub)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # 主页，自然排序
    path('article/<slug:slug>/', DetailView.as_view(), name='detail'),  # 文章内容页
    path('article-edit/<slug:slug>/', DetailEditView.as_view(), name='article_edit'),  # 文章编辑
    path('article-update/', update_article, name='article_update'),  # 文章更新
    path('category/<slug:slug>/', CategoryView.as_view(), name='category'),
    path('tag/<slug:slug>/', TagView.as_view(), name='tag'),
    path('about/', AboutView, name='about'),  # About页面
    path('timeline/', TimelineView.as_view(), name='timeline'),  # timeline页面
    path('archive/', ArchiveView.as_view(), name='archive'),  # 归档页面
    path('silian.xml', SilianView.as_view(content_type='application/xml'), name='silian'),  # 死链页面
    path('search/', MySearchView.as_view(), name='search_view'),  # 全文搜索
    path('friend/', FriendLinkView.as_view(), name='friend'),  # 友情链接
    path('friend/add/', friend_add, name='friend_add'),  # 友情链接申请
    path('dashboard/', dashboard, name='dashboard'),  # 看板
    path('feed-hub/', feed_hub, name='feedhub'),  # feed hub

    # 专题列表页
    path('subject/', SubjectListView.as_view(), name='subject_index'),
    # 专题详情页
    path('subject/<int:pk>/', SubjectPageDetailView.as_view(), name='subject_page'),
    # 专题文章内容页
    path('subject/article/<slug:slug>/', SubjectDetailView.as_view(), name='subject_detail'),

]

if settings.DEBUG:
    urlpatterns.append(path('test/', test_page_view, name='test'))

apps/comment/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import AddCommentView, NotificationView, mark_to_read, mark_to_delete

urlpatterns = [
    path('add/', AddCommentView, name='add_comment'),
    path('notification/', NotificationView, name='notification'),
    path('notification/no-read/', NotificationView, {'is_read': 'false'}, name='notification_no_read'),
    path('notification/mark-to-read/', mark_to_read, name='mark_to_read'),
    path('notification/mark-to-delete/', mark_to_delete, name='mark_to_delete'),
]

apps/oauth/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import profile_view, change_profile_view


urlpatterns = [
    path('profile/',profile_view,name='profile'),
    path('profile/change/',change_profile_view,name='change_profile'),

]

apps/tool/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import (Toolview, BD_pushview, BD_pushview_site,
                    regexview, useragent_view, html_characters,
                    docker_search_view, editor_view, word_cloud,
                    json2go, tax, query_ip,
                    )

urlpatterns = [
    path('', Toolview, name='total'),  # 工具汇总页
    path('baidu-linksubmit/', BD_pushview, name='baidu_push'),  # 百度主动推送
    path('baidu-linksubmit-sitemap/', BD_pushview_site, name='baidu_push_site'),  # 百度主动推送sitemap
    path('regex/', regexview, name='regex'),  # 正则表达式在线
    path('user-agent/', useragent_view, name='useragent'),  # user-agent生成器
    path('html-special-characters/', html_characters, name='html_characters'),  # HTML特殊字符查询
    path('docker-search/', docker_search_view, name='docker_search'),  # docker镜像查询
    path('markdown-editor/', editor_view, name='markdown_editor'),  # editor.md 工具
    path('word-cloud/', word_cloud, name='word_cloud'),  # 词云图 工具
    path('json2go/', json2go, name='json2go'),  # json转go
    path('tax/', tax, name='tax'),  # 个人所得税年度汇算
    path('ip/', query_ip, name='ip'),  # 查询IP
]

izone/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from blog.feeds import AllArticleRssFeed
from blog.views import robots

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
                  path('favicon.ico', RedirectView.as_view(url='/static/blog/img/favicon.svg')),
                  path('adminx/', admin.site.urls),
                  path('accounts/', include('allauth.urls')),  # allauth
                  path('accounts/', include(('oauth.urls', 'oauth'), namespace='oauth')),
                  # oauth,只展现一个用户登录界面
                  path('', include(('blog.urls', 'blog'), namespace='blog')),  # blog
                  path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
                  # comment
                  path('robots.txt', robots, name='robots'),  # robots
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
                       name='django.contrib.sitemaps.views.sitemap'),  # 网站地图
                  path('feed/', AllArticleRssFeed(), name='rss'),  # rss订阅
                  path('resume/', include(('resume.urls', 'resume'), namespace='resume')),  # 个人简历
                  path('nav/', include(('webstack.urls', 'webstack'), namespace='webstack')),

                  path('rss/', include(('rsshub.urls', 'rsshub'), namespace='rsshub')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

if settings.API_FLAG:
    from api.urls import router

    urlpatterns.append(path('api/v1/', include((router.urls, router.root_view_name),
                                               namespace='api')))  # restframework

if settings.TOOL_FLAG:
    urlpatterns.append(path('tool/', include(('tool.urls', 'tool'), namespace='tool')))  # tool

apps/blog/models.py
import json
from datetime import datetime
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import markdown
import re


# Create your models here.

# 文章关键词，用来作为SEO中keywords
class Keyword(models.Model):
    name = models.CharField('文章关键词', max_length=20)

    class Meta:
        verbose_name = '关键词'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name


# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240, default='标签描述',
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag', kwargs={'slug': self.slug})

    def get_article_list(self):
        """返回当前标签下所有发表的文章列表"""
        return Article.objects.filter(tags=self, is_publish=True)


# 文章分类
class Category(models.Model):
    name = models.CharField('文章分类', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述', max_length=240, default='分类描述',
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category', kwargs={'slug': self.slug})

    def get_article_list(self):
        return Article.objects.filter(category=self, is_publish=True)


# 专题
class Subject(models.Model):
    STATUS_CHOICES = (
        ('not_started', '未开始'),
        ('ongoing', '连载中'),
        ('completed', '已完结'),
    )

    name = models.CharField('专题名称', max_length=50)
    status = models.CharField('状态', max_length=20, choices=STATUS_CHOICES, default='not_started')
    description = models.CharField('描述', max_length=250)
    sort_order = models.IntegerField('排序', default=99, help_text='作为专题列表页的排序')
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    cover_image = ProcessedImageField(upload_to='subject/upload/%Y/%m/%d/',
                                      default='subject/default/default.png',
                                      verbose_name='封面图',
                                      processors=[ResizeToFill(250, 150)],
                                      help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px'
                                      )

    class Meta:
        verbose_name = '专题'
        verbose_name_plural = verbose_name
        ordering = ['sort_order']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:subject_page', kwargs={'pk': self.pk})

    def get_topics(self):
        """得到一个专题的所有主题，按照排序进行排序"""
        return Topic.objects.filter(subject=self).order_by('sort_order', '-pk')

    def get_article_count(self):
        """获取专题下文章数量"""
        num = 0
        for each in self.get_topics():
            num += each.get_articles().count()
        return num

    def get_article_list(self):
        """
        返回一个专题下文章的列表，这个跟显示的一致，可以用来得到上下文
        @return:
        """
        article_list = []
        for topic in self.get_topics():
            article_list.extend(topic.get_articles())
        return article_list

    def get_status_color(self):
        """返回对应状态的颜色"""
        text_dict = {
            'not_started': 'danger',
            'ongoing': 'info',
            'completed': 'success'
        }
        return text_dict[self.status]


# 专题的主题，作为专题的目录，专题-主题-文章
class Topic(models.Model):
    name = models.CharField('主题名称', max_length=50)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    sort_order = models.IntegerField('排序', default=99, help_text='仅作为主题在专题中的排序，类似目录')

    subject = models.ForeignKey(Subject, verbose_name='所属专题', on_delete=models.PROTECT,
                                related_name='topics')

    class Meta:
        verbose_name = '专题-主题'
        verbose_name_plural = verbose_name
        ordering = ['sort_order']

    def __str__(self):
        return f'[{self.subject.name}]{self.name}'

    def get_absolute_url(self):
        return reverse('blog:subject_page', kwargs={'pk': self.subject.pk}) + f'#{self.name}'

    def get_articles(self):
        """得到一个主题的所有已发布的文章，按照主题排序排序"""
        return Article.objects.filter(is_publish=True, topic=self).order_by('topic_order', '-pk')


# 文章
class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='作者',
                               on_delete=models.PROTECT)
    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField('文章摘要', max_length=230, default='文章摘要等同于网页description内容，请务必填写...')
    body = models.TextField(verbose_name='文章内容')
    img_link = ProcessedImageField(upload_to='article/upload/%Y/%m/%d/',
                                   default='article/default/default.png',
                                   verbose_name='封面图',
                                   processors=[ResizeToFill(250, 150)],
                                   blank=True,
                                   help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px'
                                   )
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    views = models.IntegerField('阅览量', default=0)
    slug = models.SlugField(unique=True)
    is_top = models.BooleanField('置顶', default=False)
    is_publish = models.BooleanField('是否发布', default=True)

    category = models.ForeignKey(Category, verbose_name='文章分类', on_delete=models.PROTECT)
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    keywords = models.ManyToManyField(Keyword, verbose_name='文章关键词',
                                      help_text='文章关键词，用来作为SEO中keywords，最好使用长尾词，3-4个足够')

    # 跟专题-主题相关的字段和关系，都是非必填，仅给专题的时候使用，其他地方一概不用
    # 设计上一个专题有多个主题（目录的概念），一个主题可以有多个文章，一个文章只能归属一个主题
    topic = models.ForeignKey(Topic, verbose_name='所属主题', on_delete=models.SET_NULL,
                              null=True, blank=True, related_name='articles')
    topic_order = models.IntegerField('主题中排序', default=99, null=True, blank=True,
                                      help_text='仅作为文章在主题中的排序')
    topic_short_title = models.CharField('主题短标题', max_length=50, null=True, blank=True,
                                         help_text='专门给Topic使用的短标题')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return f'{self.title[:30]}...' if len(self.title) > 30 else self.title

    def save(self, *args, **kwargs):
        # 当为更新且is_publish由False变更成True的时候才执行: 发布的文章时间的创建时间以发布时间为准
        if self.pk and self.is_publish and Article.objects.filter(pk=self.pk,
                                                                  is_publish=False).exists():
            self.create_date = datetime.now()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """优先使用专题地址"""
        if self.topic:
            return self.get_subject_absolute_url()
        return reverse('blog:detail', kwargs={'slug': self.slug})

    def get_subject_absolute_url(self):
        """获取专栏地址"""
        return reverse('blog:subject_detail', kwargs={'slug': self.slug})

    def body_to_markdown(self):
        return markdown.markdown(self.body, extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self):
        """
        有主题则只能返回这个主题所属专题下的文章，否则返回空，没有主题则按照pk返回
        @return:
        """
        if self.topic:
            subject_articles = self.topic.subject.get_article_list()
            for index, article in enumerate(subject_articles):
                if article.pk == self.pk and index != 0:
                    return subject_articles[index - 1]
            return

        return Article.objects.filter(id__lt=self.id, is_publish=True).order_by('-id').first()

    def get_next(self):
        if self.topic:
            subject_articles = self.topic.subject.get_article_list()
            for index, article in enumerate(subject_articles):
                if article.pk == self.pk and index != len(subject_articles) - 1:
                    return subject_articles[index + 1]
            return

        return Article.objects.filter(id__gt=self.id, is_publish=True).order_by('id').first()

    def get_topic_title(self):
        """仅当有主题的时候优先使用短标题，这个函数给专题使用"""
        if self.topic:
            return self.topic_short_title or self.title
        return self.title


# 时间线
class Timeline(models.Model):
    COLOR_CHOICE = (
        ('primary', '基本-蓝色'),
        ('success', '成功-绿色'),
        ('info', '信息-天蓝色'),
        ('warning', '警告-橙色'),
        ('danger', '危险-红色')
    )
    SIDE_CHOICE = (
        ('L', '左边'),
        ('R', '右边'),
    )
    STAR_NUM = (
        (1, '1颗星'),
        (2, '2颗星'),
        (3, '3颗星'),
        (4, '4颗星'),
        (5, '5颗星'),
    )
    side = models.CharField('位置', max_length=1, choices=SIDE_CHOICE, default='L')
    star_num = models.IntegerField('星星个数', choices=STAR_NUM, default=3)
    icon = models.CharField('图标', max_length=50, default='fa fa-pencil')

apps/blog/templates/blog/tags/base_right.html
{% load blog_tags static %}
{% load dashboard %}

<!--个人空间-->
<div class="card border-0 rounded-6 px-3 mb-2 mb-md-3 d-none d-lg-block" id="home-card">
    <div class="card-header bg-none px-0">
        <strong><i class="fa fa-flag mr-2 f-17"></i>博客空间</strong>
    </div>
    <div class="card-body px-0 pt-3 pb-1">
        <div class="row text-center">
            <div class="col">
                <a href="https://github.com/zhangmoumou1/izone" target="_blank" title="查看博客源码">
                    <img style="max-width:40px" alt="博客源代码" src="{% static 'blog/img/github.png' %}">
                    <p class="mt-2">博客源码</p>
                </a>
            </div>
            <div class="col">
                <a href="{% url 'blog:timeline' %}" target="_blank" title="查看网站建站历程">
                    <img style="max-width:40px" alt="网站的建站历程" src="{% static 'blog/img/blog.png' %}">
                    <p class="mt-2">更新记录</p>
                </a>
            </div>
            <div class="col">
                <a href="{% url 'rss' %}" target="_blank" title="订阅博客">
                    <img style="max-width:40px" alt="订阅博客RSS" src="{% static 'blog/img/rss.png' %}">
                    <p class="mt-2">RSS订阅</p>
                </a>
            </div>
        </div>
        {% get_blog_infos as blog_infos %}
        <div class="row text-center blog-info-list">
            <div class="col">
                <div>
                    <p class="mt-1 badge">{{ blog_infos.article }}</p>
                    <p class="mt-1">文章</p>
                </div>
            </div>
            <div class="col">
                <div>
                    <p class="mt-1 badge">{{ blog_infos.subject }}</p>
                    <p class="mt-1">专题</p>
                </div>
            </div>
            <div class="col">
                <div>
                    <p class="mt-1 badge">{{ blog_infos.tag }}</p>
                    <p class="mt-1">标签</p>
                </div>
            </div>
            <div class="col">
                <div>
                    <p class="mt-1 badge">{{ blog_infos.comment }}</p>
                    <p class="mt-1">评论</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!--阅读榜单，至少5篇文章才显示，最多显示10篇文章-->
{% get_hot_article_list as hot_article_list %}
{% if hot_article_list|length >= 5 %}
    <div class="card border-0 rounded-6 px-3 mb-2 mb-md-3" id="article-view-card">
        <div class="card-header bg-none px-0">
            <strong><i class="fa fa-fire mr-2 f-17"></i>昨日热榜</strong>
        </div>
        <ul class="article-view-list list-group list-group-flush f-14">
            {% for hot_article in hot_article_list|slice:":10" %}
                <li class="py-2">
                    <a href="{{ hot_article.get_absolute_url }}"
                       data-last-views="{{ hot_article.add_view }}">{{ hot_article.title }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
<!--文章分类-->
<div class="card border-0 rounded-6 px-3 mb-2 mb-md-3" id="category-card">
    <div class="card-header bg-none px-0">
        <strong><i class="fa fa-book mr-2 f-17"></i>文章分类</strong>
    </div>
    {% get_category_list as categories %}
    <ul class="list-group list-group-flush f-16">
        {% for each in categories %}
            <li class="list-group-item d-flex justify-content-between align-items-center pr-2 py-2">
                <a class="category-item" href="{{ each.get_absolute_url }}"
                   title="查看【{{ each.name }}】分类下所有文章">{{ each.name }}</a>
                <span class="badge text-center" title="当前分类下有{{ each.total_num }}篇文章">{{ each.total_num }}</span>
            </li>
        {% endfor %}
    </ul>
</div>
<!--标签云-->
<div class="card border-0 rounded-6 px-3 mb-2 mb-md-3" id="tag-card">
    <div class="card-header bg-none px-0">
        <strong><i class="fa fa-tags mr-2 f-17"></i>标&nbsp;签&nbsp;云</strong>
    </div>
    <div class="card-body px-0 py-3">
        <div class="tag-cloud">
            {% get_tag_list as tag_list %}
            {% for tag in tag_list %}
                <a href="{{ tag.get_absolute_url }}" class="tags f-16" id="tag-{{ forloop.counter }}"
                   title="【{{ tag.name }}】标签下有{{ tag.total_num }}篇文章">{{ tag.name }}</a>
            {% endfor %}
        </div>
    </div>
</div>

apps/blog/templates/blog/tags/navbar.html
{% load static oauth_tags comment_tags %}
<nav class="navbar navbar-expand-md bg-white fixed-top blog-navbar py-md-0">
    <a class="navbar-brand d-md-none d-lg-block" id="site-logo-name" href="{% url 'blog:index' %}">
        <strong class="px-2">{{ site_logo_name }}</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                {% url 'blog:index' as index_url %}
                <a class="nav-link py-md-3 {% if request.path == index_url %}active{% endif %}"
                   href="{{ index_url }}">首页<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                {% url 'blog:subject_index' as subject_index_url %}
                <a class="nav-link py-md-3 {% if request.path == subject_index_url %}active{% endif %}"
                   href="{{ subject_index_url }}">专题</a>
            </li>
            <li class="nav-item">
                {% url 'blog:archive' as archive_url %}
                <a class="nav-link py-md-3 {% if request.path == archive_url %}active{% endif %}"
                   href="{{ archive_url }}">归档</a>
            </li>
            {% if tool_flag %}
                <li class="nav-item">
                    {% url 'tool:total' as tool_url %}
                    <a class="nav-link py-md-3 {% if request.resolver_match.namespace == 'tool' %}active{% endif %}"
                       href="{{ tool_url }}">在线工具</a>
                </li>
            {% endif %}
            <li class="nav-item">
                {% url 'webstack:webstack_index' as webstack_index_url %}
                <a class="nav-link py-md-3 {% if request.path == webstack_index_url %}active{% endif %}"
                   href="{{ webstack_index_url }}">网址导航</a>
            </li>
{#            <li class="nav-item">#}
{#                {% url 'blog:feedhub' as feed_hub_url %}#}
{#                <a class="nav-link py-md-3 {% if request.path == feed_hub_url %}active{% endif %}"#}
{#                   href="{{ feed_hub_url }}">Feed Hub</a>#}
{#            </li>#}
            {% if api_flag %}
                <li class="nav-item d-xs-block d-sm-none d-lg-block">
                    <a class="nav-link py-md-3" href="{% url 'api:api-root' %}" target="_blank">API</a>
                </li>
            {% endif %}

            <!-- 个人外链 -->
            {% if private_links %}
                <li class="nav-item dropdown d-xs-block d-sm-none d-lg-block">
                    <a class="nav-link dropdown-toggle py-md-3" href="#" id="more-link" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true"
                       aria-expanded="false"
                    >个人外链</a>
                    <div class="dropdown-menu dropdown-menu-left mt-0 border-0"
                         aria-labelledby="navbarDropdown">
                        {% for link_item in private_links %}
                            <a class="dropdown-item pl-3" href="{{ link_item.link }}" target="_blank"
                               title="{{ link_item.title }}">
                                <i class="fa fa-fw {{ link_item.icon }} text-info mr-2"></i>{{ link_item.name }}</a>
                        {% endfor %}
                    </div>
                </li>
            {% endif %}
            <li class="nav-item">
                {% url 'blog:friend' as friend_url %}
                <a class="nav-link py-md-3 {% if request.path == friend_url %}active{% endif %}"
                   href="{{ friend_url }}">友情链接</a>
            </li>
            <li class="nav-item mr-2">
                {% url 'blog:about' as about_url %}
                <a class="nav-link py-md-3 {% if request.path == about_url %}active{% endif %}"
                   href="{{ about_url }}">关于</a>
            </li>
            <form class="nav-item navbar-form py-md-2 mr-2" role="search" method="get" id="searchform"
                  action="{% url 'blog:search_view' %}">
                <div class="input-group">
                    <input type="search" name="q" class="form-control" placeholder="站内搜索" autocomplete="off"
                           required>
                    <div class="input-group-btn">
                        <button class="btn btn-info" type="submit" aria-label="文章搜索">
                            <i class="fa fa-search"></i>
                        </button>
                    </div>
                </div><!-- /input-group -->
            </form>
        </ul>
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
                {% get_notifications_count user 'false' as msgnum %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false" title="{{ user.username }}，欢迎回来！">
                        {% if msgnum > 0 %}
                            <span class="get-msg text-center">{{ msgnum }}</span>
                        {% endif %}
                        {% get_user_avatar_tag user %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right mt-0 border-0"
                         aria-labelledby="navbarDropdown">
                        <a class="dropdown-item pl-3" href="{% url 'oauth:profile' %}"><i
                                class="fa fa-fw fa-user text-info mr-2"></i>个人资料</a>
                        {% if user.is_staff %}
                            <a class="dropdown-item pl-3" href="{% url 'admin:index' %}"><i
                                    class="fa fa-fw fa-key text-info mr-2"></i>后台管理</a>
                            <a class="dropdown-item pl-3" href="{% url 'blog:dashboard' %}"><i
                                    class="fa fa-fw fa-tachometer text-info mr-2"></i>网站看板</a>
                            <a class="dropdown-item pl-3" href="{% url 'admin:blog_article_add' %}"><i
                                    class="fa fa-fw fa-plus text-info mr-2"></i>新增文章</a>
                        {% endif %}
                        {% url 'comment:notification_no_read' as no_read_url %}
                        {% url 'comment:notification' as read_url %}
                        <a class="dropdown-item pl-3"
                           href="{% if msgnum > 0 %}{{ no_read_url }}{% else %}{{ read_url }}{% endif %}">
                            <i class="fa fa-fw fa-bell text-info mr-2"></i>消息
                            {% if msgnum > 0 %}
                                <span class="badge badge-warning ml-3 text-center">{{ msgnum }}</span>
                            {% endif %}
                        </a>
                        <a class="dropdown-item pl-3" href="{% url 'account_logout' %}"><i
                                class="fa fa-fw fa-sign-out text-info mr-2"></i>退出</a>
                    </div>
                </li>
            {% else %}
                <li class="nav-item mr-2">
                    <a class="nav-link py-md-3" href="{% url 'account_login' %}?next={{ request.path }}">登录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link py-md-3" href="{% url 'account_signup' %}?next={{ request.path }}">注册</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

apps/blog/templates/blog/tags/pagecut.html
{% load blog_tags %}
<div class="page-inner text-center">
    {% if page_obj.has_previous %}
        {% deal_with_full_path request.get_full_path 'page' page_obj.previous_page_number as new_pre_page_path %}
        <a href="{{ new_pre_page_path }}"><span class="n">上一页</span></a>
    {% endif %}
    {% for page in page_range %}
        {% if page_obj.number == page %}
            <span class="page-active">{{ page }}</span>
        {% elif page == "..." %}
            <span class="mx-0" style="background: none;width:1rem">{{ page }}</span>
        {% else %}
            {% deal_with_full_path request.get_full_path 'page' page as page_path %}
            <a href="{{ page_path }}"><span>{{ page }}</span></a>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        {% deal_with_full_path request.get_full_path 'page' page_obj.next_page_number as new_next_page_path %}
        <a href="{{ new_next_page_path }}"><span class="n">下一页</span></a>
    {% endif %}
</div>