apps/oauth/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from .views import profile_view, change_profile_view


urlpatterns = [
    path('profile/',profile_view,name='profile'),
    path('profile/change/',change_profile_view,name='change_profile'),

]

izone/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic import RedirectView

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap
from blog.feeds import AllArticleRssFeed
from blog.views import robots

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}

urlpatterns = [
                  path('favicon.ico', RedirectView.as_view(url='/static/blog/img/favicon.svg')),
                  path('adminx/', admin.site.urls),
                  path('accounts/', include('allauth.urls')),  # allauth
                  path('accounts/', include(('oauth.urls', 'oauth'), namespace='oauth')),
                  # oauth,只展现一个用户登录界面
                  path('', include(('blog.urls', 'blog'), namespace='blog')),  # blog
                  path('comment/', include(('comment.urls', 'comment'), namespace='comment')),
                  # comment
                  path('robots.txt', robots, name='robots'),  # robots
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
                       name='django.contrib.sitemaps.views.sitemap'),  # 网站地图
                  path('feed/', AllArticleRssFeed(), name='rss'),  # rss订阅
                  path('resume/', include(('resume.urls', 'resume'), namespace='resume')),  # 个人简历
                  path('nav/', include(('webstack.urls', 'webstack'), namespace='webstack')),

                  path('rss/', include(('rsshub.urls', 'rsshub'), namespace='rsshub')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 加入这个才能显示media文件

if settings.API_FLAG:
    from api.urls import router

    urlpatterns.append(path('api/v1/', include((router.urls, router.root_view_name),
                                               namespace='api')))  # restframework

if settings.TOOL_FLAG:
    urlpatterns.append(path('tool/', include(('tool.urls', 'tool'), namespace='tool')))  # tool

apps/oauth/models.py
import os

from django.db import models
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

from django.conf import settings


class Ouser(AbstractUser):
    link = models.URLField('个人网址', blank=True, help_text='提示：网址必须填写以http开头的完整形式')
    avatar = ProcessedImageField(upload_to='avatar/upload/%Y/%m/%d/%H-%M-%S',
                                 default='avatar/default/default.png',
                                 verbose_name='头像',
                                 processors=[ResizeToFill(80, 80)]
                                 )

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username

apps/oauth/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Ouser

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Ouser
        fields = ['link','avatar']

apps/oauth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .forms import ProfileForm
from django.contrib import messages
import os


# Create your views here.

@login_required
def profile_view(request):
    return render(request, 'oauth/profile.html')


@login_required
def change_profile_view(request):
    if request.method == 'POST':
        old_avatar_file = request.user.avatar.path
        old_avatar_url = request.user.avatar.url
        # 上传文件需要使用request.FILES
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            if not old_avatar_url == '/media/avatar/default.png':
                if os.path.exists(old_avatar_file):
                    os.remove(old_avatar_file)
            form.save()
            # 添加一条信息,表单验证成功就重定向到个人信息页面
            messages.add_message(request, messages.SUCCESS, '个人信息更新成功！')
            return redirect('oauth:profile')
    else:
        # 不是POST请求就返回空表单
        form = ProfileForm(instance=request.user)
    return render(request, 'oauth/change_profile.html', context={'form': form})

apps/oauth/templates/oauth/change_profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block metas %}
    <meta name="description" content="用户账号管理，使用django-allauth社交用户系统，支持微博、Github等社交账号登录，加入{{ site_end_title }}，查看更多信息。">
    <meta name="keywords" content="django-allauth,社交用户系统,OAuth 2.0">
{% endblock %}

{% block top-file %}
<link href="{% static 'blog/css/account.css' %}?v=20171229.01966" rel="stylesheet">
{% endblock %}

{% block head_title%}个人信息修改{% endblock%}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">
            <div class="card px-3 px-lg-4">
                <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">修改资料</h3></div>
                <div class="card-body">
                    <form class="change_profile" method="post" enctype="multipart/form-data"
                          action="{% url 'oauth:change_profile'%}">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button class="btn btn-info btn-sm" type="submit">更新资料</button>
                    </form>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="login-title"><span>更多操作</span></div>
                    <div class="more-link mt-3">
                        <a class="btn btn-info btn-sm mx-3" href="{% url 'oauth:profile' %}">查看资料</a>
                        <a class="btn btn-info btn-sm mx-3" href="{% url 'account_change_password' %}">修改密码</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/oauth/templates/oauth/profile.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load blog_tags oauth_tags %}
{% load static %}

{% block metas %}
    <meta name="description" content="用户账号管理，使用django-allauth社交用户系统，支持微博、Github等社交账号登录，加入{{ site_end_title }}，查看更多信息。">
    <meta name="keywords" content="django-allauth,社交用户系统,OAuth 2.0">
{% endblock %}

{% block top-file %}
<link href="{% static 'blog/css/account.css' %}?v=20171229.01966" rel="stylesheet">
{% endblock %}

{% block head_title%}个人资料{% endblock%}

{% block base_content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">
            <div class="card px-3 px-lg-4">
                <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">个人资料</h3></div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item text-center border-0" id="profile-avatar">
                            {% get_user_avatar_tag user %}
                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">用户名：</span>
                            <span>{{ user.username }}</span>
                        </li>
                        {% for emailaddress in user.emailaddress_set.all %}
                        {% if emailaddress.primary or user.emailaddress_set.count == 1 %}
                        <li class="list-group-item ml-5 border-0" title="提示：已验证邮箱的用户有更多特权！">
                            <span class="font-weight-bold">邮&emsp;箱：</span>
                            <span>{{ emailaddress.email }}</span>
                            {% if emailaddress.verified %}
                                <span class="badge badge-primary">已验证</span>
                            {% else %}
                                <span class="badge badge-danger">未验证</span>
                            {% endif %}
                        </li>
                        {% endif %}
                        {% endfor %}
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">网&emsp;址：</span>
                            <span>{{ user.link }}</span>
                        </li>
                    </ul>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="login-title"><span>更多操作</span></div>
                    <div class="more-link mt-3">
                        <a class="btn btn-info btn-sm mx-lg-3 mx-sm-2" href="{% url 'oauth:change_profile' %}">修改资料</a>
                        <a class="btn btn-info btn-sm mx-lg-3 mx-sm-2" href="{% url 'account_change_password' %}">修改密码</a>
                        <a class="btn btn-info btn-sm mx-lg-3 mx-sm-2" href="{% url 'account_email' %}">邮箱验证</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}